# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c411ec97d28d3f8263ec471473f875644eb8b94f09beed1a21db59b797dc5c666d17dc4c5ca9132861d6bd3db9f74e0f43211bdc8a56108f9ddd8baf78e235a7

test:
  secret_key_base: c1924fa196dec15d79904e716191aff8c1589aad2dcfa5b4a153e83c48e11c07954d0ddb56a2dc2260c984fba0eb78a16e30d2dcbf4663de46e714d0266e71a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
